name: Grafters
favicon: null
layout_spectrum: 0.22133675822988153
typography_spectrum: 0.6058338249567896
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2051245435141027
  lightness: 0.39796929783187807
  saturation: 0.062097641406580806
  rhythmicContrast: 0.6452274101320654
purpose: []
